apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-container
      image: busybox
      command: ["sh", "-c", "echo $GITA && sleep 3600"]
      env:
        - name: GITA
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: GITA

