apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: prod
spec:
  type: NodePort  # LoadBalancer-ადაც შეიძლება, თუ cloud-ში ხარ
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8080      # External Port (სადაც შევდივართ)
      targetPort: 80  # Pod-ის შიდა პორტი
      nodePort: 30080 # Cluster-ის გარეთ მისაწვდომი პორტი

